const SUPABASE = {
  URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  ANON: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SERVICE_ROLE: process.env.NEXT_SUPABASE_SERVICE_ROLE,
  DB_PASSWORD: process.env.NEXT_SUPABASE_DB_PASSWORD,
  STORAGE_BUCKET: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
};

const KAKAO_API_KEY = process.env.KAKAO_REST_API_KEY;

export { SUPABASE, KAKAO_API_KEY };